[project]
authors = ["Bob"]
entry = "main.sw"
license = "Apache-2.0"
name = "wallet_contract"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", branch = "master" }
wallet_lib = { path = "../wallet_lib" }
